{% set name = "myproxyclient" %}
{% set version = "2.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 0a309413dddff370f4bfc4ad30030575a4be0846afd464cf61f8164942c77241

build:
  noarch: python
  number: 0
  entry_points:
    - myproxyclient = myproxy.client.script:main
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - pyopenssl
    - python >=3.6
    - six
  run:
    - pyopenssl
    - python >=3.6
    - six

test:
  imports:
    - myproxy
    - myproxy.client
    - myproxy.client.test
    - myproxy.client.utils
  commands:
    - myproxyclient --help

about:
  home: "https://github.com/cedadev/MyProxyClient"
  license: BSD-3-Clause
  license_family: BSD
  license_file: myproxy/client/LICENSE
  summary: "Python client implementation of MyProxy credential management service"
  doc_url: https://github.com/cedadev/MyProxyClient#readme
  dev_url: https://github.com/cedadev/MyProxyClient
description: |
    This a pure Python implementation of a client to the MyProxy Credential
    Management Server (http://grid.ncsa.uiuc.edu/myproxy/).
    It provides both a Python API and a command line interface.
extra:
  recipe-maintainers:
    - agoodm
    - jarifibrahim
    - cofinoa
